# Cancer classification prediction-benign/malignant breast cancer tumor prediction

## background

- Data description  
1. The download address of the original data:  
      https://archive.ics.uci.edu/ml/machine-learning-databases/  
2. Data description

(1)  699 samples, a total of 11 columns of data, the first column is the id retrieved by the term, and the last 9 columns are related to the tumor

Related medical characteristics, the last column indicates the value of the tumor type.

(2)  Contains 16 missing values, marked with "?".

## Frame  
1. Load the data set
2. Basic data processing  
2.1. Missing value processing  
2.2. Select features and targets  
2.3. Data segmentation  
3. Feature engineering ( Data standardization )
4. Machine learning (Logic regression)
5. Model evaluation


## Implementation

### Import the module

In [43]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score
import ssl
ssl._create_default_https_context = ssl._create_unverified_context


### Load the data set

In [2]:
names = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']

In [3]:
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data",
                  names=names)

In [4]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [5]:
data[data["Marginal Adhesion"] == "?"]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)


Empty DataFrame
Columns: [Sample code number, Clump Thickness, Uniformity of Cell Size, Uniformity of Cell Shape, Marginal Adhesion, Single Epithelial Cell Size, Bare Nuclei, Bland Chromatin, Normal Nucleoli, Mitoses, Class]
Index: []

In [6]:
data.shape

(699, 11)

### Basic data processing

#### Missing value processing

In [7]:
data = data.replace(to_replace="?", value=np.NAN)

In [8]:
data = data.dropna()

In [9]:
data.shape

(683, 11)

#### Select features and targets

In [10]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [11]:
x = data.iloc[:, 1: 10]
x.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                  1                            2           1   
1                  5                            7          10   
2                  1                            2           2   
3                  1                            3           4   
4                  3                            2           1   

   Bland Chromatin  Normal Nucleoli  Mitoses  
0                3                1        1  
1                3                2        1  
2                3                1        1  
3                3                7        1  
4                3                1        1

In [12]:
y = data["Class"]
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

####  Data segmentation

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state = 22)

In [14]:
x_train.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
502                4                        1                         1   
474                5                        1                         1   
358                8                       10                         5   
410                1                        1                         1   
210                8                       10                        10   

     Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
502                  2                            2           1   
474                  1                            2           1   
358                  3                            8           4   
410                  1                            2           1   
210                 10                            5          10   

     Bland Chromatin  Normal Nucleoli  Mitoses  
502                2                1        1  
474                1                1        1  
358                4               10        3  
410                2                1        1  
210                8               10        6

### Feature engineering  
- Data standardization

In [15]:
transfer = StandardScaler()

In [16]:
x_train = transfer.fit_transform(x_train)

In [17]:
type(x_train)

numpy.ndarray

In [18]:
x_train[:4]

array([[-0.17630888, -0.70477256, -0.74442891, -0.28670271, -0.55418586,
        -0.70812549, -0.61483944, -0.61252907, -0.35289401],
       [ 0.17493683, -0.70477256, -0.74442891, -0.63956758, -0.55418586,
        -0.70812549, -1.04964301, -0.61252907, -0.35289401],
       [ 1.22867397,  2.26921276,  0.62169153,  0.06616216,  2.18288643,
         0.12216516,  0.25476772,  2.34300386,  0.74547518],
       [-1.23004603, -0.70477256, -0.74442891, -0.63956758, -0.55418586,
        -0.70812549, -0.61483944, -0.61252907, -0.35289401]])

In [19]:
x_test = transfer.transform(x_test)

In [20]:
x_test[:4]

array([[ 0.17493683, -0.70477256, -0.74442891, -0.63956758, -0.09800715,
        -0.43136194, -0.61483944, -0.28413652, -0.35289401],
       [ 1.9311654 ,  1.27788432,  1.30475175,  0.06616216,  2.18288643,
         0.39892871,  1.55917846,  0.37264857,  0.74547518],
       [-0.5275546 , -0.04388694,  0.62169153, -0.28670271, -0.09800715,
         1.78274646,  1.55917846, -0.61252907, -0.35289401],
       [-0.5275546 , -0.70477256, -0.74442891, -0.63956758, -0.55418586,
        -0.70812549, -0.61483944, -0.61252907, -0.35289401]])

### Machine learning (Logic regression)

In [21]:
estimator = LogisticRegression()

In [22]:
estimator.fit(x_train,y_train)

LogisticRegression()

### Model evaluation

- prediction

In [26]:
y_predict = estimator.predict(x_test)

In [27]:
y_predict[:4]

array([2, 4, 4, 2], dtype=int64)

- Accuracy  
$(TP+TN) /(TP+TN+FN+FP)$

In [31]:
estimator.score(x_test,y_test)

0.9766081871345029

- Precision  
$TP/(TP+FP)$  
- Recall  
$TP/(TP+FN)$  
- F1 score (robustness of the model)
$ F 1=\frac{2 T P}{2 T P+F N+F P}=\frac{2 \cdot \text { Precision } \cdot \text { Recall }}{\text { Precision }+\text { Recall }} $

In [36]:
ret = classification_report(y_test, 
                           y_predict, 
                           labels=(2,4), 
                            target_names=("Benign tumor","Malignant tumor")
                           )

In [38]:
print(ret)

                 precision    recall  f1-score   support

   Benign tumor       0.98      0.98      0.98       111
Malignant tumor       0.97      0.97      0.97        60

       accuracy                           0.98       171
      macro avg       0.97      0.97      0.97       171
   weighted avg       0.98      0.98      0.98       171



- ROC - AUC

In [39]:
y_test = np.where(y_test > 3, 1,0)

In [42]:
y_test[:4]

array([0, 1, 1, 0])

In [45]:
roc_auc_score(y_test, y_predict)

0.9743243243243243